version: '3.9'

services:
    cotizador-database-service:
        build:
            context: ..
            dockerfile: docker/Dockerfile.dev
        command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8010
        volumes:
            - ../:/usr/src/app/
        ports:
            - "8002:8010"
        env_file:
            - ../.env
        networks:
            - cotizador
        depends_on:
            - cotizador-postgres-db
        restart: on-failure
            
    cotizador-postgres-db:
        build:
            context: ../config_db
            dockerfile: Dockerfile
        volumes:
            - cotizador-postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        networks:
            - cotizador

networks:
    cotizador:
        external: True

volumes:
    cotizador-postgres:
        external: true